title: 남기혁
subtitle: 고민이 많은 개발자
description: >- # this means to ignore newlines until "baseurl:"
  남기혁-고민이 많은 개발자

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    # - text: Gallery
    #   url: /gallery
    # - text: Shop
    #   url : /shop
    # - text: Contact
    #   url : /contact
    # - text: Styleguide
    #   url: /styleguide
    # - text: Get Started
    #   url: /get-started

# Edit Author details (For multi authors check _data/authors.yml)

author_logo: noah.jpg
author: Noah Nam
author_bio: Hi, my name is Noah Nam. I am working as an back-end engineer :)
author_email: "noah85.Nam@gmail.com"
author_location: South Korea
author_website_url: "https://noahnam.github.io"
typewrite-text: 엔지니어링은 사회에 기여하는 방향으로 발전해야 한다는 신념을 가지고 일하는 개발자 입니다. 

# Experiences
author_work_experiences:
            - company_name: Apartalk
              company_logo: google.png
              company_url: https://www.notion.so/apartalk/
              designation: CTO
              description: Worked on various Apartalk Products
              visibility: true
            - company_name: CUPIST
              company_logo: cupist.png
              company_url: https://medium.com/cupist
              designation: Software Engineer
              description: Worked on GLAM Application Product / Social Team Lead
              visibility: true
            - company_name: Nuriinfos
              company_logo: nuri.png
              company_url: https://www.nis.co.kr/
              designation: Software Engineer
              description: Worked on various PRM Solution Products / Lab
              visibility: true

# Education
author_education_details:
              - college_logo: sung.jpeg
                college_name: 공학 석사
                college_url: https://www.skku.edu/
                college_degree: 성균관대학교
                description: Bigdata of Technology
                visibility: true
              - college_logo: cbnu.png
                college_name: 공학사
                college_url: https://www.chungbuk.ac.kr/
                college_degree: 충북대학교
                description: Electrical engineering
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: true

# social links
twitter_username: null
github_username:  noahNam
facebook_username: null
linkedin_username: 기혁-남-7716131a0
behance_username: null
instagram_username: chacha_seoha
medium_username: null
telegram_username: null
dribbble_username: null
flickr_username: null

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )
#disqus_shortname: noahnam-github-io
hyvor_talk_website_id: 3793

# wakatime username (coding activity)
wakatime_username: noah85

# mailchimp embedded form url (newsletter):
# mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: noah85.Nam@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build

theme: jekyll-theme-dinky